spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agent
    username: agent
    password: agent
  web:
    cors:
      allowed-origins: '*'
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/v1
      completions-path: /chat/completions
      embeddings-path: /embeddings
qdrant:
  host: localhost
  port: 6334  # gRPC port
  collection-name: documents
  vector-size: 384
  vector-name: text_embedding    # Named vector identifier
  distance: Cosine              # Cosine, Dot, Euclid, Manhattan
  on-disk: false               # RAM storage for better performance
  use-tls: false               # RAM storage for better performance
  hnsw-config:                 # HNSW index configuration
    m: 16                      # Connections per element (higher = better recall, more memory)
    ef-construct: 100          # Search quality during index construction
    full-scan-threshold: 10000 # When to use brute force vs HNSW
    max-indexing-threads: 0    # Parallel threads (0 = auto-detect)
  refresh: false               # Create clear collection
logging:
  level:
    pl.ejdev:.agent: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
app:
  features: pubmed,orcid
  jwt:
    secret: 5JzoMbk6E5qIqHSuBTgeQCARtUsxAkBiHwdjXOSW8kWdXzYmP3X51C0